### ISSUE TITLE
Suggestions Megathread

### ISSUE THREAD

**Issue by PatheticMustan** [rebels2638/PartsApp#2]
We have a few things we need to finish up.

## TODO

- [ ]  Item View, apparently @KryptoCrash has a solution at home.
- [x]  About page, I'd like @grgwnw to work on it, but I could also do it.
- [ ]  Refactor, our code is pretty horrible right now, I'll fix it later.
- [X]  Fix the conflicts in #1, and merge it.
- [ ]  Implement Favorites system.
- [x]  Test our app on BOTH iOS and Android, because that's where our apps will be anyways.
- [x]  Make the repo public, and ask Nick to move it under the Robotics org.

### ItemView

We have a ListItem that contains a name, and the type (part/list). The ItemView should list all the images in an image carousel.

### About Page

The images for the about page need to be uploaded, and if somebody could copy paste the text over, that'd be pretty sweet.

### Refactor

After we finish the app, we can polish it by removing unnecessary code, fix any bugs that may arise, and optimize the images. Images will cause lots of bloat, so we definitely need to make them smaller.

### Fix #1 

Somebody please do this I hate merges and conflicts

### Implement Favorite System

We should give each part/tool a unique numerical ID, so that we can later store an array of ints that just point to the favorited items.
Favoriting includes:

- Swipe right on list item to favorite in the parts/tools menu
- Swipe left on list item to unfavorite in the favorites menu
- (Un)Favorite button on parts/tools/favorite/item view
- Store favorite list locally, there's probably an API for that.

### App Testing

I have no idea how we're going to get an iOS device to test on.
Remember that our apps have to **_MAINLY SUPPORT SMALL SCREENS!_**

### Public Repo

This would be a nice bonus, and open source things are very hip and cool.
